spring:
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console/
      settings:
        web-allow-others: true

  # Kafka
  kafka:
    bootstrap-servers: <subdomain>.confluent.cloud:9092

    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      security.protocol: SASL_SSL
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<key>' password='<secret>';

      # Kafka Schema Registry
      schema.registry.url: <subdomain>.confluent.cloud
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: <key>:<secret>

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
      auto-offset-reset: earliest

    # A missing topic on the broker will not fail the application startup
    listener:
      missing-topics-fatal: false

# Logging
logging:
  level:
    root: DEBUG