spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console/
      settings:
        web-allow-others: true